Add std:: check to CI

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -24,3 +24,17 @@ jobs:
          else
           echo "All good"
          fi
+
+  find-missing-std:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Run check for missing std
+        run: |
+          IDENTIFIERS="uint8_t uint16_t uint32_t uint64_t int8_t int16_t int32_t int64_t size_t"
+          for identifier in $IDENTIFIERS; do
+            if grep -rE -n "$identifier" | grep -v "std::$identifier"; then
+              echo "[ERROR] found $identifier without std:: prefix"
+              exit 1
+            fi
+          done
