Formatting

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -18,12 +18,12 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: Run todo check
-        run: | 
-         if grep -rE -n 'TODO|FIXME' * | grep -v 'TODOLater'; then
+        run: |
+          if grep -rE -n 'TODO|FIXME' * | grep -v 'TODOLater'; then
           exit 1
-         else
+          else
           echo "All good"
-         fi
+          fi
 
   find-missing-std:
     runs-on: ubuntu-latest
@@ -33,10 +33,10 @@ jobs:
         run: |
           IDENTIFIERS="uint8_t uint16_t uint32_t uint64_t int8_t int16_t int32_t int64_t size_t"
           for identifier in $IDENTIFIERS; do
-            if grep -rE -n "$identifier" | grep -v "std::" | grep -v "lint.yml"; then
-              echo "[ERROR] found $identifier without std:: prefix"
-              exit 1
-            fi
+          if grep -rE -n "$identifier" | grep -v "std::" | grep -v "lint.yml"; then
+        echo "[ERROR] found $identifier without std:: prefix"
+          exit 1
+          fi
           done
 
   find-redundant-hyped:
@@ -47,6 +47,6 @@ jobs:
         run: |
           cd lib
           if grep -rE -n "hyped::" | grep -v "namespace"; then
-            echo "[ERROR] found redundant hyped:: prefix"
-            exit 1
+        echo "[ERROR] found redundant hyped:: prefix"
+          exit 1
           fi
